PATH "./data"
VERTICAL "./testcorp.vrt"
DEFAULTATTR word
ATTRIBUTE word
ATTRIBUTE lemma
ATTRIBUTE lc {
    DYNLIB internal
    DYNTYPE freq
    DYNAMIC utf8lowercase
    FROMATTR word
}
STRUCTURE s
STRUCTURE doc {
    ATTRIBUTE id
    ATTRIBUTE date
}
