pub mod corp;
pub mod lex;
pub mod structure;
pub mod rev;
pub mod text;
pub mod bits;
pub mod wsketch;
pub mod wrbits;
pub mod writerev_dense;
pub mod writerev_sparse;
pub mod writerev_temp;
pub mod virtual_corp;
pub mod reservoir_sampling;
mod util;
